
Vagrant.configure("2") do |config|

    ### BOX
    config.vm.box               = "bento/ubuntu-20.04"
    config.vm.provider :virtualbox do |vbox|
        vbox.name               = "backuppc"
        vbox.customize [ 
          "modifyvm",           :id,
          "--description",      "backuppc",
          "--memory",           "1024",
          "--vram",             128,
          "--vrde",             'off',
        ]
    end

    ### NETWORK
    config.vm.network(:private_network, {ip: '10.17.17.17',  netmask: '255.255.0.0'})

    ### PROVISION
    config.vm.provision "shell", inline: "echo 'somepass' | sudo tee /root/password"
    config.vm.provision "file",  source: "../backuppc-ubuntu-installer", destination: "/tmp/backuppc-ubuntu-installer"
    config.vm.provision "shell", inline: "sudo sh /tmp/backuppc-ubuntu-installer"

end

